spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/docker_release_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none